name: Run Pytest Tests

on:
  push:
    branches:
      - main # O cualquier otra rama en la que quieras ejecutar las pruebas
  pull_request:
    branches:
      - main  # Ejecutar pruebas cuando se haga un pull request hacia la rama principal

jobs:
  test:
    runs-on: ubuntu-latest  # Esto indica que se ejecutará en un contenedor de Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Revisa tu código fuente desde GitHub

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./test  # Establece el directorio de trabajo a test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener las dependencias en requirements.txt

      - name: Create folder for words
        working-directory: ./test
        run: |
          mkdir words
          
      - name: Run process_text.py script
        working-directory: ./test  # Establece el directorio de trabajo a test
        run: |
          python process_text.py  # Ahora se ejecuta en la carpeta test

      - name: Run tests with pytest
        working-directory: ./test  # Establece el directorio de trabajo a test
        run: |
          pytest test_processing.py  # Ejecuta pytest en la carpeta test
